env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WatpyvVud2miWyBeF2W7NwGCLaAQc07uT0vhydUtuGpSoq4CDOCKdAwTIAnVtpqrNbfiDEkMVBpIkWvsIntVYIbbRGetQKhH3eZ1gdgAvIVS7JpTJLauMZLGsSydjj2dlAS8Y2q8UNVtfWG/9VPg0loypgzxnRlcqErYuWYjzNE="
   # Coverity run condition (avoid matrix multiple runs), need customized
   # build script. Need an update if new matrix cases.
   - coverity_scan_run_condition='"$CC" = gcc -a "$TRAVIS_OS_NAME" != osx'
   # Coverity script test mode (if true no uploading, avoid reaching the quota)
   # usual processing: false.
   - coverity_scan_script_test_mode=false
   # Travis CI has 1.5 cores per VM, take advantage of it
   - MAKEFLAGS="-j 2"

os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc
  fast_finish: true

before_install:
  - env
  - df
  - date -u
  - uname -a
  - export J='-j3'

install:
  - git submodule update --init --recursive

# CImg is now downloaded by CImg/Makefile, no need to install it
#  - sudo apt-get install cimg-dev

script:
  - if [[ ${COVERITY_SCAN_BRANCH} == 1 ]];
    then
      echo "Don't build on coverity_scan branch.";
      exit 0;
    fi
  - make $J CONFIG=debug
  - make $J nomulti CONFIG=debug
  - if [ "$CC" = "gcc" ]; then
      make -C CImg clean;
      make -C CImg CONFIG=debug CXXFLAGS_ADD=-fopenmp LDFLAGS_ADD=-fopenmp;
    fi

addons:
  coverity_scan:
    # customized build script URL
    # TRAVIS_REPO_SLUG: owner_name/repo_name of repository currently being built
    # TRAVIS_BRANCH: name of the branch currently being built
    build_script_url: https://raw.githubusercontent.com/$TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/.travis-coverity-scan-build.sh
    # project metadata
    project:
      name: $TRAVIS_REPO_SLUG
    # Where email notification of build analysis results will be sent
    notification_email: frederic.devernay@m4x.org
    # Commands to prepare for build_command
    #build_command_prepend: ./configure
    # This command will be added as an argument to "cov-build" to compile
    # the project for analysis
    build_command: "make $J CONFIG=debug"
    # Pattern to match selecting branches that will run analysis
    branch_pattern: coverity_scan
